addIngredient("human",{
    type:"meat",
    color:"#b81d32",
    keywords:"flesh","meat",
});
addIngredient("fetus",{
    color:"#fa8989",
    type:"meat",
    shape:"embryo",
  keywords:"human,embryo,baby",
});
addIngredient("hand",{
    color:"#ffaf87",
    type:"meat",
    shape:"four_splay",
  keywords:"human",
});
addIngredient("blood",{
    color:"#fd0000",
    type:"liquid",
  adj:"bloody",
  keywords:"human,heart",
  reactions: {
        bacteria: {set1:"infected_blood"},
    infected_blood: {set1:"infected_blood"},
    poison: {set1:"infected_blood"},
  }
});
addIngredient("infected_blood",{
    color:"d40047",
    type:"liquid",
  adj:"infected",
    hidden:true,
});
addIngredient("heart",{
    type:"meat",
    color:"e30242",
  shape:"heart",
  adj:"lovely",
    keywords:"human,organ",
});
addIngredient("intenstines",{
    type:"meat",
    color:"bf2654",
  shape:"noodles",
    scale:"1.5",
  keywords:"human,organ",
});
addIngredient("brain",{
    type:"meat",
    color:"f23d67",
  shape:"brain",
  adj:"intelligent",
    scale:"1.25",
  keywords:"human,organ",
});
addIngredient("stomach",{
    type:"meat",
    color:"ff87cb",
  shape:"bean_l",
  keywords:"human,organ",
});
addIngredient("liver",{
    type:"meat",
    color:"6b1c1c",
  shape:"bean_l",
    scale:"1.25",
  keywords:"human,organ",
});
addIngredient("kidney",{
    type:"meat",
    color:"7d1111",
  shape:"bean",
  keywords:"human,organ",
});
addIngredient("ear",{
    type:"meat",
    color:"ffaf87",
  shape:"ear",
  keywords:"human,organ",
});
addIngredient("eyeball",{
    type:"meat",
    color:"ffadad",
  shape:"ball_strung",
  keywords:"human,organ",
});
addRecipe("fetus+poison","abortion");
addRecipe("fetus+knife","abortion");
addRecipe("broth+brain","brain_stew");
addRecipe("alcohol+liver","hepatitis");
addRecipe("hand+hand","high_five!");
addRecipe("blood+alcohol","really_bloody_mary");
addRecipe("brain+ice_cream","brain_freeze");
addRecipe("brain+ice_cube","brain_freeze");
addRecipe("kidney+rock","kidney_stone");
